apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluentd
bases:
  - ../elk
resources:
- namespace.yaml
- rbac.yaml
- daemonset.yaml
configMapGenerator:
- name: fluentd
  files:
    - fluent.conf