apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logflow
spec:
  selector:
    matchLabels:
      app: logflow
  template:
    metadata:
      labels:
        app: logflow
      annotations:
        logflow.io/exclude: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: logflow
        image: santhoshkt/logflow:1.0.1
        env:
          - name: GODEBUG
            value: memprofilerate=0
        resources:
          limits:
            cpu: 0.1
        volumeMounts:
          - name: var
            mountPath: /var
          - name: config
            mountPath: /etc/logflow
      volumes:
      - name: var
        hostPath:
          path: /var
      - name: config
        configMap:
          name: logflow
      serviceAccountName: logflow
