apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logflow
commonLabels:
  app: logflow
resources:
- rbac.yaml
- daemonset.yaml
configMapGenerator:
- name: logflow
  files:
    - logflow.conf