apiVersion: v1
kind: ServiceAccount
metadata:
  name: logflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logflow
rules:
- apiGroups: ['']
  resources: ["pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logflow
subjects:
- kind: ServiceAccount
  name: logflow