apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluent-bit
bases:
  - ../elk
resources:
- namespace.yaml
- rbac.yaml
- daemonset.yaml
configMapGenerator:
- name: fluent-bit-config
  files:
    - fluent-bit.conf
    - parsers.conf
