apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logflow
bases:
  - ../elk
  - ../../kustomize
resources:
- namespace.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: logflow
  path: remove_resources.yaml
