apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logflow
bases:
  - ../elk
  - ../../kustomize
resources:
- namespace.yaml
patchesStrategicMerge:
- remove_resource_limits.yaml
